spring: 
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/1811b?user=root&password=root&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2b8
   data-username: root
   data-password: root
 server:
  port:8091
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka
